### PR TITLE
Added TypeScript support.

### LINKED ISSUE #1: Typescript Support

### LINKED ISSUE #7: Missing flavor text causes the bot to crash
The flavor text is not always present for every language. The app should check this and omit the flavor text if not present. Right now, the app assumes that there is always at least one flavor text present, which causes it to crash in some cases.

### LINKED ISSUE #10: Tests and test folder
Move all tests to a `test` folder in the root directory.

### PR DESCRIPTION
**Pull request by drazenbebic**
Resolves #1 
Resolves #7
Resolves #10

### CODE REVIEW

**Comment by drazenbebic** [comment]
@tbal999 I think the tests are failing because they haven't been written for TypeScript. Can you take a look and update this branch please?

**Comment by drazenbebic** [comment]
@tbal999 I reran the checks and they failed 😭 

I think we need to do a bit more. Let me know if you want me to take a look with you. Here's some additional info:

https://jestjs.io/docs/getting-started#using-typescript

**Comment by tbal999** [comment]
I just renamed the file to .ts hoping it would work.

Looks like it's more complex than that. I will refer to the link you shared & learn more about typescript :)

**Comment by drazenbebic** [comment]
One thing I noticed right away is that the instantiation of the Pokedex is missing. Somewhere in your test, before you call any methods on the `Pokedex`, you need to instantiate it like so:

`const Pokedex = new PokedexModule();`

Had to rename it to `PokedexModule` so the there's no naming conflict.

**Comment by drazenbebic** [comment]
Resolves #10

**Pull request merged**
